version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_USER: user
      MYSQL_PASSWORD: password
#    volumes:
#      - ./docker-mysql:/var/lib/mysql  # Store MySQL data in a local directory
      #- ./docker-mysql:/docker-entrypoint-initdb.d # Seed the database if there are no data
    ports:
      - "3306:3306"
